<a href="https://colab.research.google.com/github/Sameerdev512/Numpy-Bascis/blob/main/ML_Day1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. Write a NumPy program to create a 1D array from a list [1, 2, 3, 4, 5].
import numpy as np

# Create a list
my_list = [1, 2, 3, 4, 5]

# Convert list to NumPy array
array = np.array(my_list)

# Print the array
print(array)


[1 2 3 4 5]


In [ ]:
#2. Create a NumPy array of shape (3, 3) filled with zeros.
import numpy as np

arr = np.array([[0,0,0],[0,0,0],[0,0,0]])

print(arr)
print(arr.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
(3, 3)


In [ ]:
#3. Create a NumPy array of shape (2, 4) filled with ones.
import numpy as np

list = [0,0,0,0]

arr = np.array([list,list])
print(arr)
print(arr.shape)

[[0 0 0 0]
 [0 0 0 0]]
(2, 4)


In [ ]:
#2. Create a NumPy array of shape (3, 3) filled with zeros.
#3. Create a NumPy array of shape (2, 4) filled with ones.
import numpy as np

arr = np.zeros((3,3))
print(arr)
print(arr.shape)

arr2 = np.ones((2,4))
print(arr2)
print(arr.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 3)


In [ ]:
#4. Generate an array of numbers from 10 to 50 with a step of 5.
# Not including 50
arr = np.arange(10,50,5)

print(arr)

[10 15 20 25 30 35 40 45]


In [ ]:
#5. Create an array of 10 evenly spaced values between 0 and 1.
import numpy as np

# Generate 10 numbers between 0 and 1
# endpoint = true will include 1
# endpoint = false will not include 1
array_without_endpoint = np.linspace(0, 1, num=10, endpoint=False)

print(array_without_endpoint)


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
#6. Generate a 5x5 identity matrix.
import numpy as np

matrix = np.ones((5,5))
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#7. Create an array of shape (3,3) with random values between 0 and 1.
import numpy as np

# 1st argument --> numbers ranging from 0 to 1,
# 2nd argument, row = 3, col = 3
array = np.random.randint(2, size=(3, 3))
print(array)

[[0 1 0]
 [1 1 1]
 [1 1 0]]


In [ ]:
#8. Convert a Python list [10, 20, 30] into a NumPy array and print its type.
import numpy as np
list = [4,8,5,2]

arr = np.array(list)
print(arr)

[4 8 5 2]


In [ ]:
#9. Create an array of 10 random integers between 1 and 100.
import numpy as np

arr = np.random.randint(1,100,(10))
print(arr)

[67 91 82 82 83 50 59 22 31 45]


In [ ]:
#10. Generate a 4x4 array with random floating-point numbers.
import numpy as np

arr = np.random.uniform(1,100,(4,4))
print(arr)

[[ 8.89605331 64.06958833 72.88327652 78.53363601]
 [15.5704975  91.62926006 98.72989935 80.70580611]
 [84.28067975 14.86229807 71.70531207 76.21531707]
 [41.17374726 49.78689918 36.75323285 52.97583074]]


#Array Manipulation





In [ ]:
#11. Reshape a 1D array of 9 elements into a 3x3 matrix.
import numpy as np

arr = [1,2,3,4,5,6,7,8,9]
matrix = np.reshape(arr,(3,3))
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#12. Flatten a 2D NumPy array into a 1D array.
ini_array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

# printing initial arrays
print("initial array", str(ini_array1))

# using reshape method
# result = np.reshape(ini_array1,(9))

#using flatten method
result = ini_array1.flatten();

# printing result
print("New resulting array: ", result)

initial array [[1 2 3]
 [2 4 5]
 [1 2 3]]
New resulting array:  [1 2 3 2 4 5 1 2 3]


In [ ]:
#13. Stack two NumPy arrays vertically.
arr1 = [1,2,3]
arr2 = [4,5,6]

#arrange vertically row-wise
result = np.vstack((arr1,arr2))
print(result)


[[1 2 3]
 [4 5 6]]


In [ ]:
#14. Stack two NumPy arrays horizontally.
arr1 = [1,2,3]
arr2 = [4,5,6]

#arrange horizontally column-wise
result = np.hstack((arr1,arr2))
print(result)


[1 2 3 4 5 6]


In [ ]:
#15. Concatenate two 1D NumPy arrays.
arr1 = [1,2,3]
arr2 = [4,5,6]

result = np.concatenate((arr1,arr2))
print(result)


[1 2 3 4 5 6]


In [ ]:
#16. Split an array [1,2,3,4,5,6] into three equal parts.
arr = np.array([1,2,3,4,5,6])

splited_arr = np.split(arr,3)
print(splited_arr)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#17. Change the data type of a NumPy array from float to int.
arr = np.array([1,2,3,4])

print("initial type - ", arr.dtype)

#changing type int to float
array_float = arr.astype(float)

print(array_float)
print("final type - ",array_float.dtype)

initial type -  int64
[1. 2. 3. 4.]
final type -  float64


In [ ]:
#18. Reverse a NumPy array.
arr = [1,2,3,4,5]

result = arr[::-1]
print(result)

[5, 4, 3, 2, 1]


In [ ]:
#19. Find the shape and size of a given NumPy array.
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("size = " , arr.size ," and shape = ",arr.shape)


size =  6  and shape =  (2, 3)


In [ ]:
#20. Create an array and find its transpose.

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

result = arr.T

print(result)


[[1 4 7]
 [2 5 8]
 [3 6 9]]


#Mathematical Operation


In [2]:
#21. Add two NumPy arrays element-wise.
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.add(arr1,arr2)
print(result)

[5 7 9]


In [4]:
#22. Subtract two NumPy arrays element-wise.
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.subtract(arr1,arr2)
print(result)

[-3 -3 -3]


In [5]:
#23. Multiply two NumPy arrays element-wise.
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.multiply(arr1,arr2)
print(result)

[ 4 10 18]


In [9]:
#23. Divide two NumPy arrays element-wise.
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.divide(arr1,arr2)
print(result)

[0.25 0.4  0.5 ]


In [7]:
#25. Compute the dot product of two matrices.
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.dot(arr1,arr2)
print(result)

32


In [10]:
#26. Find the sum of all elements in a NumPy array.
arr = np.array([1,2,3])

result = np.sum(arr)
print(result)

6


In [11]:
#27. Compute the mean of a NumPy array.
arr = np.array([1,2,3])

result = np.mean(arr)
print(result)

2.0


In [14]:
#28. Compute the median of a NumPy array.
arr = np.array([1,2,3,4,5,6])

result = np.median(arr)
print(result)

3.5


In [15]:
#29. Compute the standard deviation of a NumPy array.
arr = np.array([1,2,3,4,5,6])

result = np.std(arr)
print(result)

1.707825127659933


In [16]:
#30. Compute the variance of a NumPy array.
arr = np.array([1,2,3,4,5,6])

result = np.var(arr)
print(result)

2.9166666666666665


#Indexing and Slicing


In [20]:
#31.Extract the first row from a 2D NumPy array.
import numpy as np
arr = np.array([[1,2],[3,4]])
print(arr)
print(arr[0])

[[1 2]
 [3 4]]
[2 4]


In [21]:
#32.Extract the last column from a 2D NumPy array.
import numpy as np
arr = np.array([[1,2],[3,4]])
print(arr)
print(arr[:,-1])

[[1 2]
 [3 4]]
[2 4]


In [22]:
#33.Extract the all even numbers from a 2D NumPy array.
import numpy as np
arr = np.array([[1,2],[3,4]])
print(arr)
print(arr[arr % 2 ==0])

[[1 2]
 [3 4]]
[2 4]


In [25]:
#34. Replace all negative values in an array with zero.
arr = np.array([[1,-2],[3,4]])
print(arr)
arr[arr < 0] = 0
print(arr)

[[ 1 -2]
 [ 3  4]]
[[1 0]
 [3 4]]


In [26]:
#35. Assign a new value to a specific index in a NumPy array.
arr = np.array([[1,-2],[3,4]])
arr[0][0] = 12
print(arr)

[[12 -2]
 [ 3  4]]


In [38]:
#36. Find the index of a specific value in a NumPy array.
arr = np.array([1,2,3,4,3,5,6,7,8,9])

#print all indexx where 3 is present
result  = np.where(arr == 3)[0]

#print only frost index where 3 occurs
result2  = np.where(arr == 3)[0][0]

print(result)
print(result2)

[2 4]
2


In [39]:
#37. Use boolean indexing to filter values greater than a given threshold.
arr = np.array([1,2,3,4,5,6,7,8,9])

threshold = 5

result = arr[arr > threshold]

print(result)

[6 7 8 9]


In [49]:
#38. Use slicing to extract a subarray from a 3x3 matrix.
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

#taking 3 elements from last two row
sub2 = matrix[:2,:2]
sub1 = matrix[-2:,:3]

print(sub1)
print(sub2)

[[4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


In [50]:
#39. Get the top 3 maximum values from an array.
arr = np.array([1,45,21,7,81,554,3,484,4])

#sorting and taking last three numbers from last index are maximum
result = np.sort(arr)[-3:]

print(result)

[ 81 484 554]


In [51]:
#40. Get the indices of all nonzero elements in an array.
arr = np.array([1,0,5,1,0,8,0,548,0,54,4])

result = np.where(arr == 0)[0]

print(result)

[1 4 6 8]


#Logical and Statistical Funstions


In [53]:
#41. Find the unique values in a NumPy array.
arr = np.array([10,5,48,0,5,1,5,15,5,48,2,45,4,1])

#reuturn all values that is appeared
result = np.unique(arr)
print(result)

[ 0  1  2  4  5 10 15 45 48]


In [54]:
#42. Count the occurrence of each unique value in a NumPy array.
# Create a NumPy array with duplicate values
arr = np.array([10, 20, 30, 10, 40, 20, 50, 30, 10])

# Find unique values and their counts
unique_values, counts = np.unique(arr, return_counts=True)

print("Unique Values:", unique_values)
print("Counts:", counts)

Unique Values: [10 20 30 40 50]
Counts: [3 2 2 1 1]


In [59]:
#43. Find the maximum and minimum values in a NumPy array.
arr = np.array([5,4,2,8,7,5,4,2,1])

min = np.sort(arr)[:1]
max = np.sort(arr)[-1:]
print(min)
print(max)

[1]
[8]


In [62]:
#44. Get the index of the maximum value in an array.
arr = np.array([10, 20, 30, 10, 40, 20, 50, 30, 10])

result_index = np.argmax(arr)
print(result_index)
print(arr[result_index])

6
50


In [63]:
#45. Get the index of the minimum value in an array.
arr = np.array([10, 20, 30, 10, 40, 20, 50, 30, 10])

result_index = np.argmin(arr)
print(result_index)
print(arr[result_index])

0
10


In [65]:
#46. Compute the cumulative sum of a NumPy array.
arr = np.array([10,20,30,40])

result = np.cumsum(arr)
print(result)

[ 10  30  60 100]


In [66]:
#47. Compute the cumulative product of a NumPy array.
arr = np.array([1,2,3,4,5])

result = np.cumprod(arr)
print(result)

[  1   2   6  24 120]


In [68]:
#48. Check if a NumPy array contains any NaN values.
arr = np.array([1,5,4,2,np.nan])

result = np.isnan(arr)
result2 = np.any(np.isnan(arr))

print(result)
print(result2)

[False False False False  True]
True


In [72]:
#49. Replace NaN values with 0 in a NumPy array.
arr = np.array([1,5,14,2,np.nan])

result = np.nan_to_num(arr, nan=0)
print(result)

[ 1.  5. 14.  2.  0.]


In [73]:
#50. Count the number of nonzero elements in an array.
arr = np.array([1,4,5,1,0,4,5,1])

result = np.count_nonzero(arr)
print(result)

7


In [74]:
#50. Count the number of zero elements in an array.
arr = np.array([1,4,5,1,0,4,5,1])

result = np.count_nonzero(arr == 0)
print(result)

1
