<a href="https://colab.research.google.com/github/Sameerdev512/Numpy-Bascis/blob/main/ML_Numpy_Tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Broadcsating and Advance Operation

In [ ]:
#51. Add a scalar value to all elements of an array.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
scalar = 10
result = arr + scalar
print(result)

[11 12 13 14 15]


In [ ]:
#52. Multiply an array by a scalar value.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
scalar = 10
result = arr * scalar
print(result)

[10 20 30 40 50]


In [ ]:
#53. Divide all elements of an array by a scalar.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
scalar = 10
result = arr / scalar
print(result)

[0.1 0.2 0.3 0.4 0.5]


In [ ]:
#54. Compute the exponential of all elements in an array.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = np.exp(arr)
print(result)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [ ]:
#55. Compute the logarithm of an array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = np.log(arr)
print(result)

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
#56. Compute the sine of all elements in an array.
arr = np.array([1,2,3,4,5])

result = np.sin(np.radians(arr))
print(arr)

[1 2 3 4 5]


In [ ]:
#57. Compute the cosine of all elements in an array.
arr = np.array([1,2,3,4,5])

result = np.cos(np.radians(arr))
print(result)

[0.9998477  0.99939083 0.99862953 0.99756405 0.9961947 ]


In [ ]:
#58. Compute the square root of all elements in an array.
arr = np.array([1,2,3,4,5])

result = np.sqrt(arr)
print(result)

[1.         1.41421356 1.73205081 2.         2.23606798]


In [ ]:
#59. Compute the absolute value of all elements in an array.
arr = np.array([-1,-2,-3,-4,-5])

result = np.abs(arr)
print(result)


[1 2 3 4 5]


In [ ]:
#60. Find the element-wise maximum of two arrays.
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,5,4,2,8])

result = np.maximum(arr1,arr2)
print(result)

[3 5 4 4 8]


#Searching and Sorting


In [ ]:
#61. Sort a NumPy array in ascending order.
import numpy as np
arr = np.array([4,7,5,9,2,3,4])

result = np.sort(arr)
print(result)

[2 3 4 4 5 7 9]


In [ ]:
#62. Sort a NumPy array in descending order.
import numpy as np
arr = np.array([4,7,5,9,2,3,4])

result = np.sort(arr)[::-1]
print(result)

[9 7 5 4 4 3 2]


In [ ]:
#63. Sort a 2D NumPy array along a specific axis.
import numpy as np

arr = np.array([[5, 2, 9],
                [1, 7, 6],
                [8, 3, 4]])

# Sort along axis=0 (column-wise sorting)
sorted_col = np.sort(arr, axis=0)
print("Sorted along columns:\n", sorted_col)

# Sort along axis=1 (row-wise sorting)
sorted_row = np.sort(arr, axis=1)
print("Sorted along rows:\n", sorted_row)
print(arr.shape)

Sorted along columns:
 [[1 2 4]
 [5 3 6]
 [8 7 9]]
Sorted along rows:
 [[2 5 9]
 [1 6 7]
 [3 4 8]]
(3, 3)


In [ ]:
#64. Find the k smallest values in a NumPy array.
arr = np.array([2,4,5,9,6,8,7])
k = 3

# k smallest values
result = np.sort(arr)[:k]
print(result)

[2 4 5]


In [ ]:
#65. Find the k largest values in a NumPy array.
arr = np.array([2,4,5,9,6,8,7])
k = 3

#last k largest values (sorting array in descending)
result = np.sort(arr)[::-1][:3]
print(result)

[9 8 7]


In [ ]:
#66. Use argsort() to get the sorted indices of an array.
arr = np.array([2,4,5,9,6,8,7])

result = np.argsort(arr)
print(result)

[0 1 2 4 6 5 3]


In [ ]:
#67. Search for a specific value in an array and return its index.
arr = np.array([2,4,5,9,6,8,7])
val = 4

result = np.where(arr == val)[0][0]
print(result)

1


In [ ]:
#68. Find the first occurrence of an element greater than a given value.
arr = np.array([2,5,9,6,8,7,4])
val = 4

result = np.where(arr > val)[0][0]
print(result)

1


In [ ]:
#69. Use where() to replace values based on a condition.
#replace 5 to 0
arr = np.array([2,5,9,6,8,7,5,4])

arr[arr == 5] = 0
print(arr)

[2 0 9 6 8 7 0 4]


In [ ]:
#70. Count the occurrences of a specific value in an array.
arr = np.array([2,5,9,6,8,7,5,4])

result = np.count_nonzero(arr == 5)
print(result)

2


#Linear Algebra Operations


In [ ]:
#71. Compute the determinant of a square matrix.
import numpy as np
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

result = np.linalg.det(matrix)
print(result)

0.0


In [ ]:
#72. Compute the reverse of a square matrix.
import numpy as np
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

result = np.flip(matrix)
print(result)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
#73. Compute the rank of a square matrix.
import numpy as np
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

result = np.linalg.matrix_rank(matrix)
print(result)

2


In [ ]:
#74. Compute the eigen value of a square matrix.
import numpy as np
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

#reutrns eigenvalue and eigenvectors
eigenvalue,eigenvector = np.linalg.eig(matrix)
print(eigenvalue)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]


In [ ]:
#75. Compute the eigen vector of a square matrix.
import numpy as np
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

#reutrns eigenvalue and eigenvectors
eigenvalue,eigenvector = np.linalg.eig(matrix)
print(eigenvector)

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [ ]:
#76. Compute the single value decomposition of a square matrix.
import numpy as np
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

result = np.linalg.svd(matrix)
print(result)

SVDResult(U=array([[-0.21483724,  0.88723069,  0.40824829],
       [-0.52058739,  0.24964395, -0.81649658],
       [-0.82633754, -0.38794278,  0.40824829]]), S=array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16]), Vh=array([[-0.47967118, -0.57236779, -0.66506441],
       [-0.77669099, -0.07568647,  0.62531805],
       [-0.40824829,  0.81649658, -0.40824829]]))


In [ ]:
#77. Solve a system of linear equations using NumPy.
import numpy as np

# Define the coefficient matrix A and the constants vector b
A = np.array([[3, 2],
              [4, 1]])

b = np.array([5, 6])

# Solve for x (the unknowns)
x = np.linalg.solve(A, b)

# Print the solution
print("Solution: x =", x)


Solution: x = [1.4 0.4]


In [ ]:
#78. Compute the Frobenius norm of a matrix.
import numpy as np

# Define the matrix A
A = np.array([[1, 2],
              [3, 4]])

# Compute the Frobenius norm
frobenius_norm = np.linalg.norm(A, 'fro')

# Print the result
print(f"The Frobenius norm of the matrix is: {frobenius_norm}")


The Frobenius norm of the matrix is: 5.477225575051661


In [ ]:
#79. Compute the trace of a matrix.
import numpy as np

# Define the matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Compute the trace of the matrix
trace = np.trace(A)

# Print the result
print(f"The trace of the matrix is: {trace}")


The trace of the matrix is: 15


In [ ]:
#80. Perform Cholesky decomposition of a positive-definite matrix.
import numpy as np

# Define the positive-definite matrix A
A = np.array([[4, 12, -16],
              [12, 37, -43],
              [-16, -43, 98]])

# Compute the Cholesky decomposition
L = np.linalg.cholesky(A)

# Print the result
print("Cholesky Decomposition (L matrix):")
print(L)


Cholesky Decomposition (L matrix):
[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


#Random Number Generation


In [ ]:
#81. Generate a random integer between 10 and 50.
import numpy as np

result = np.random.randint(10,50)
print(result)

30


In [ ]:
#82. Generate an array of 5 random integers between 1 and 100.
arr = np.random.randint(1,100,size=5)
print(arr)

[62 81 45  8 32]


In [ ]:
#83. Generate an array of random numbers following a normal distribution.
arr = np.random.normal(size = 5)
print(arr)

[-0.66682551 -0.62062794  0.84209883  1.30111422 -0.22937519]


In [ ]:
#84. Generate a 3x3 matrix with random values between -1 and 1.
matrix = np.random.uniform(-1,1,(3,3))
print(matrix)

[[ 0.41246971 -0.1019212  -0.7754414 ]
 [-0.12382515 -0.52843832  0.89300629]
 [-0.72567464 -0.80236906 -0.64759529]]


In [ ]:
#85. Shuffle the elements of a NumPy array randomly.
#works on 1-d array
arr = np.array([1,2,3,4,5,6,7,8,9])

np.random.shuffle(arr)
print(arr)

[8 4 7 1 5 3 2 6 9]


In [ ]:
#87. Sample 5 random elements from a given array.
arr = [10,20,30,40,50,60,70,80,90]

#replace=False means duplicate element can't be repeated
result = np.random.choice(arr,5,replace=False)
print(result)

[30 60 60 10 70]
[10, 20, 30, 40, 50, 60, 70, 80, 90]


In [ ]:
#88. Generate a random permutation of numbers from 0 to 9.
result = np.random.permutation(10)
print(result)

[8 2 0 9 5 1 3 4 6 7]


In [ ]:
#89. Generate a 2D array of random integers with a specific shape.
import numpy as np

# Generate a 2D array of random integers with 3 rows and 4 columns
random_array = np.random.randint(10, 51, size=(3, 4))

# Print the 2D array
print("2D array of random integers:\n", random_array)


2D array of random integers:
 [[24 43 38 22]
 [22 18 23 47]
 [14 23 48 43]]


In [ ]:
#90. Create a random matrix and compute its covariance.
import numpy as np

# Generate a random matrix with 5 rows and 3 columns
random_matrix = np.random.randint(1,50,(5,3))

# Compute the covariance matrix
cov_matrix = np.cov(random_matrix, rowvar=False)

# Print the random matrix and its covariance matrix
print("Random Matrix:\n", random_matrix)
print("\nCovariance Matrix:\n", cov_matrix)


Random Matrix:
 [[41 33 24]
 [37 34 37]
 [11 14 25]
 [19 40 36]
 [32  6 45]]

Covariance Matrix:
 [[159.    40.25  19.  ]
 [ 40.25 212.8  -32.95]
 [ 19.   -32.95  78.3 ]]
